config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
# from main.views import index, contact, view_student, StudentListView
from main.views import contact, StudentListView, StudentDetailView

app_name = MainConfig.name

urlpatterns = [
    path('', StudentListView.as_view(), name='index'),
    path('contact/', contact, name='contact'),
    path('view/<int:pk>', StudentDetailView.as_view(), name='view_student'),
]

# urlpatterns = [
#     path('', StudentListView.as_view(), name='index'),
#     path('contact/', contact, name='contact'),
#     path('view/<int:pk>', view_student, name='view_student'),
# ]

# urlpatterns = [
#     path('', index, name='index'),
#     path('contact/', contact, name='contact'),
#     path('view/<int:pk>', view_student, name='view_student'),
# ]

main/models.py
from django.db import models

# Create your models here.

NULLABLE = {'blank': True, 'null': True}

class Student(models.Model):
    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    avatar = models.ImageField(upload_to='students/', verbose_name='аватар', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='учится')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


    class Meta:
        verbose_name = "студент"
        verbose_name_plural = "студенты"
        ordering = ('last_name',)

main/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView

from main.models import Student


# Create your views here.


class StudentListView(ListView):
    model = Student
    template_name = 'main/index.html'

# def index(request):
#     student_list = Student.objects.all()
#     # student_list = Student.objects.filter(is_active=True)
#     context = {
#         'object_list': student_list,
#         'title': "Главная"
#     }
#     return render(request, 'main/index.html', context)


def contact(request):
    print(request.method)
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'{name} ({email} - {message}')

    context = {
        'title': 'Контакты'
    }

    return render(request, 'main/contact.html', context)


class StudentDetailView(DetailView):
    model = Student
    template_name = 'main/student_detail.html'

# def view_student(request, pk):
#     student_item = get_object_or_404(Student, pk=pk)
#     context = {
#         'object': student_item
#     }
#     return render(request, 'main/student_detail.html', context)

# def index(request):
#     print(request.method)
#     if request.method == "POST":
#         name = request.POST.get('name')
#         email = request.POST.get('email')
#         message = request.POST.get('message')
#         print(f'{name} ({email} - {message}')
#     return render(request, 'main/index.html')

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title}}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %} album.css" rel="stylesheet">
  </head>

  <body>

    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <p> *****

            </div>
              {% include 'main/includes/inc_main_menu.html' %}
{#            <div class="col-sm-4 offset-md-1 py-4">#}
{#              <h4 class="text-white">Меню</h4>#}
{#              <ul class="list-unstyled">#}
{#                <li><a href="{% url 'main:index' %}" class="text-white">Главная</a></li>#}
{#                <li><a href="{% url 'main:contact' %}" class="text-white">Контакты</a></li>#}
{#              </ul>#}
{#            </div>#}
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">{{title}}</h1>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
{#            {{ object_list.0 }}#}
{#            {{ object_list.count }}#}
          <div class="row">

              {% block content %}
              {% endblock %}


          </div>
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>&copy; 2023 - {% now 'Y' %}</p>
       </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/holder.min.js' %}"></script>
  </body>
</html>
</title>
</head>
<body>

</body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block content %}

<div class="col-md-4">
<div class="card mb-4 box-shadow">
{#                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">#}
<div class="card-body">
  <p class="card-text">
        Офис МСК <br>
        Офис СПБ <br>
  </p>


{#                  <div class="d-flex justify-content-between align-items-center">#}
{#                    <div class="btn-group">#}
{#                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>#}
{#                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>#}
{#                    </div>#}
{#                    <small class="text-muted">9 mins</small>#}
{#                  </div>#}
</div>
</div>
</div>

<div class="col-md-4">
<div class="card mb-4 box-shadow">
{#                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">#}
<div class="card-body">
    <h2> Напишите нам</h2>>
    <form method="pos">
        {% csrf_token %}
        <input class="form-control mb-2" name="name"/>
        <input class="form-control mb-2" name="email"/>
        <textarea class="form-control mb-2" name="message"> </textarea>
        <button type="submit", class=" mb-2 btn btn-primary form-control"> Отправить </button>>
    </form>

{#                  <p class="card-text">#}
{#                        Офис МСК <br>#}
{#                        Офис СПБ <br>#}
{#                  </p>#}

</div>
</div>
</div>

{% endblock %}

main/templates/main/includes/inc_main_menu.html
<div class="col-sm-4 offset-md-1 py-4">
  <h4 class="text-white">Меню</h4>
  <ul class="list-unstyled">
    <li><a href="{% url 'main:index' %}" class="text-white">Главная</a></li>
    <li><a href="{% url 'main:contact' %}" class="text-white">Контакты</a></li>
  </ul>
</div>

main/templates/main/index.html
{% extends 'main/base.html'%}

{% block content %}

{# <div class="row">#}
<p class="card-text py-4">
         <div class="col-md-12" w-100>
            <button type="button" class="btn btn-sm btn-outline-secondary">
                  add
            </button>
         </div>
 </p>

<div class="row">
    {%  for object in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
        {#                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">#}
            <div class="card-body">
              <p class="card-text">
                    {% if object.is_active %}
                        {{ object| title }}
                    {% else %}
                        <span class="text-muted">{{ object| title }} </span>
                    {%  endif %}
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
{#                  <button type="button" class="btn btn-sm btn-outline-secondary">#}
                      <a href="{% url 'main:view_student' object.pk %}"
                         class="btn btn-sm btn-outline-secondary"> View </a>
            {#          <a href="{% url 'main:view_student' %}"> View </a>#}
                  </button>
                  <a href="#" type="button" class="btn btn-sm btn-outline-secondary">
                      Edit
                  </a>
                  <a href="#" type="button" class="btn btn-sm btn-outline-secondary">
                      Delete
                  </a>
                </div>
            {#                    <small class="text-muted">9 mins</small>#}
              </div>
            </div>
        </div>
    </div>
    {%  endfor %}
</div>

{% endblock %}

main/templates/main/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Hi, Sky!</h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="name" /><br>
        <input type="email" name="email"/><br>
        <textarea name="message"></textarea><br>
        <input type="submit" value="Отправить"/><br>
    </form>

</body>
</html>

main/templates/main/student_detail.html
{#{% load my_tags %}#}
{%  extends 'main/base.html'%}

{% block content %}
    <div class="container">
        <div class="card mb-4 box-shadow ">
            <div class="card-header d-flex align-items-center justify-content-center h-80">
                <h5 class="my-0 font-weight-normal text-truncate">Иноформация студента</h5>
            </div>
            <div class="card-body flex-column">
                  <div class="row align-items-start">
                    <div class="col">
                      Имя
                    </div>
                    <div class="col">
                      {{ object.first_name }}
                    </div>
                  </div>
                  <div class="row align-items-center">
                    <div class="col">
                      Фамилия
                    </div>
                    <div class="col">
                      {{ object.last_name }}
                    </div>
                  </div>
                  <div class="row align-items-end">
                    <div class="col">
                      Почта
                    </div>
                  </div>
            </div>
        </div>
    </div>
{% endblock %}